from .orders_per_year import transform_orders_per_year
from .top_10_customers import transform_top_10_customers
from .top_10_products_by_sales_amount import (
    transform_top_10_products_by_sales_amount,
)
from .monthly_sales_trend import transform_monthly_sales_trend
from .top_customers_by_order_count import transform_top_customers_by_order_count
from .top_10_products_by_quantity_sold import transform_top_10_products_by_quantity_sold
