
    --*******************************************
    -- Title: Revenue by Film Category Report
    -- By: R.Esmaeeli
    -- Date: 2026-07-25
    -- Version : 1.0
    -- Description:
    -- Returns total revenue generated by each film category.
    --
    --*******************************************


    SELECT
        c.category_id,
        c.name AS category_name,
        COUNT(p.payment_id) AS payment_count,
        ROUND(SUM(p.amount), 2) AS total_revenue
    FROM category c
    JOIN film_category fc
        ON c.category_id = fc.category_id
    JOIN inventory i
        ON fc.film_id = i.film_id
    JOIN rental r
        ON i.inventory_id = r.inventory_id
    JOIN payment p
        ON r.rental_id = p.rental_id
    GROUP BY
        c.category_id,
        c.name
    ORDER BY
        total_revenue DESC;